receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus:9091/write"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
